name: Build & Pack PoewrShell Module
on: push

jobs:
  Deploy-Nupkg:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: "/home/runner/.local/share/powershell/Modules/"
          key: PS-Dependancies
      - name: Build Nuspec
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          install-module JumpCloud.SDK.V1 -Force
          install-module JumpCloud.SDK.V2 -Force
          install-module JumpCloud.SDK.DirectoryInsights -Force
          . "${{ github.workspace }}/PowerShell/Deploy/BuildNuspecFromPsd1.ps1" -RequiredModulesRepo PSGallery
      - name: Add nuget sources
        shell: pwsh
        run: |
          dotnet nuget add source "https://www.powershellgallery.com/api/v2/package" --name PSGallery
      - name: Pack nuspec
        shell: pwsh
        run: |
          nuget pack "${{ github.workspace }}/PowerShell/JumpCloud Module/JumpCloud.nuspec" -Properties NoWarn=NU5111,NU5110
      - name: Validate NuPKG File
        shell: pwsh
        run: |
          $NupkgPathDirectory = (Get-ChildItem -Path:("./*.nupkg")).Directory
          $nupkgPath = (Get-ChildItem -Path:("./*.nupkg")).FullName
          Write-Host "NuPkg Path: $nupkgPath"
          mkdir $NupkgPathDirectory/nupkg_module
          unzip $nupkgPath -d $NupkgPathDirectory/nupkg_module
          $moduleRootFiles = Get-ChildItem -File -Path:("$NupkgPathDirectory/nupkg_module")
          $moduleRootDirectories = Get-ChildItem -Directory -Path:("$NupkgPathDirectory/nupkg_module")
          Write-Host "Module Files:\n$moduleRootFiles"
          Write-Host "Module Directories:\n$moduleRootDirectories"
