name: PowerShell Module CI
on: [push]
jobs:
  Publish-PowerShell-Artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      Source: "CodeArtifact"
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            PowerShell
      - shell: pwsh
        run: |
          . "./PowerShell/Deploy/BuildNuspecFromPsd1.ps1" -RequiredModulesRepo PSGallery
