name: Test on push master mockup
on:
  pull_request:
    types:
      - closed
    paths:
      - PowerShell/*
    branches:
      - SA-3607_GHA_CI_Workflow_GW

jobs:
  Hi:
    runs-on: ubuntu-latest
    environment: PublishToPSGallery
    steps:
    - name: Hello
      run: |
        echo Hi